#compdef taco
# Completion script for taco, generated by `taco completions zsh`.

# Collect dynamic values into $reply by asking the taco binary.
# Lines are `name<TAB>description`.
_taco_items() {
  reply=()
  local name description
  while IFS=$'\t' read -r name description; do
    [[ -n "$name" ]] || continue
    reply+=("${name//:/\\:}:${description}")
  done < <(command taco __complete "$1" 2>/dev/null)
}

_taco() {
  local curcontext="$curcontext" state line
  typeset -A opt_args
  local -a reply
  local -a builtins=(
    'add:Add a new command'
    'edit:Edit a command'
    'which:Show where a command is defined'
    'alias:Alias the current project to a predefined project'
    'unalias:Remove an alias from the current project'
    'rm:Remove an existing command'
    'print:Print all the commands'
    'config:Open the config file in your editor'
    'doctor:Check the config for stale projects and dead aliases'
    'completions:Generate a shell completion script'
  )

  _arguments -C \
    '--pwd=[The current working directory]:directory:_files -/' \
    '(-p --print)'{-p,--print}'[Print the current command instead of executing it]' \
    '1: :->first' \
    '*:: :->rest'

  case $state in
    first)
      # Subcommands and aliases are offered through a single _describe call, so
      # that their descriptions are aligned in a single column.
      local -a items=($builtins 'taco:Run a builtin subcommand')
      _taco_items commands
      items+=($reply)
      _describe -t commands 'taco command' items
      ;;
    rest)
      case $line[1] in
        taco)
          _describe -t subcommands 'taco builtin' builtins
          ;;
        edit|which)
          _taco_items commands
          (( ${#reply} )) && _describe -t aliases 'alias' reply
          ;;
        rm)
          _taco_items local-commands
          (( ${#reply} )) && _describe -t aliases 'alias' reply
          ;;
        alias)
          _taco_items projects
          (( ${#reply} )) && _describe -t projects 'project' reply
          ;;
        unalias)
          _taco_items aliases
          (( ${#reply} )) && _describe -t aliases 'alias' reply
          ;;
        print)
          _arguments '(-j --json)'{-j,--json}'[Print commands in JSON format]'
          ;;
        completions)
          _values 'shell' zsh bash fish
          ;;
        config)
          ;;
        doctor)
          _arguments '--fix[Remove the reported issues from the config]'
          ;;
        *)
          _default
          ;;
      esac
      ;;
  esac
}

if [[ "$funcstack[1]" == "_taco" ]]; then
  _taco "$@"
else
  compdef _taco taco
fi
