# Completion script for taco, generated by `taco completions bash`.

# Dynamic values come from the hidden `taco __complete` subcommand, which
# prints `name<TAB>description` lines; only the names are used here.
_taco_dynamic() {
  command taco __complete "$1" 2>/dev/null | cut -f1
}

_taco() {
  local cur first
  cur="${COMP_WORDS[COMP_CWORD]}"
  first="${COMP_WORDS[1]}"

  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=($(compgen -W "add edit which alias unalias rm ls config doctor completions taco $(_taco_dynamic commands)" -- "$cur"))
    return
  fi

  case "$first" in
    taco)
      COMPREPLY=($(compgen -W "add edit which alias unalias rm ls config doctor completions" -- "$cur"))
      ;;
    add)
      COMPREPLY=($(compgen -W "--local" -- "$cur"))
      ;;
    edit)
      COMPREPLY=($(compgen -W "$(_taco_dynamic commands) --local" -- "$cur"))
      ;;
    which)
      COMPREPLY=($(compgen -W "$(_taco_dynamic commands)" -- "$cur"))
      ;;
    rm)
      COMPREPLY=($(compgen -W "$(_taco_dynamic local-commands) --local" -- "$cur"))
      ;;
    alias)
      COMPREPLY=($(compgen -W "$(_taco_dynamic projects)" -- "$cur"))
      ;;
    unalias)
      COMPREPLY=($(compgen -W "$(_taco_dynamic aliases)" -- "$cur"))
      ;;
    completions)
      COMPREPLY=($(compgen -W "zsh bash fish" -- "$cur"))
      ;;
    ls|print)
      COMPREPLY=($(compgen -W "--json --verbose" -- "$cur"))
      ;;
    config)
      COMPREPLY=($(compgen -W "--local" -- "$cur"))
      ;;
    doctor)
      COMPREPLY=($(compgen -W "--fix" -- "$cur"))
      ;;
  esac
}

complete -o default -F _taco taco
